# Generated by Django 5.1.6 on 2025-03-06 02:53

import django.core.validators
import imageuploadapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0002_alter_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.FileField(upload_to='dogs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'pdf']), imageuploadapp.models.validate_file_mimetype]),
        ),
    ]
